# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.001'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.002'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.003'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.004'

- script: |
    cd $(Agent.TempDirectory)
    cd %Agent.TempDirectory%
    dir
    echo test
  displayName: 'Run a multi-line script'
