# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.001'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.002'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.003'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'devkitPro.zip.004'

- script: |
    cd $(Agent.TempDirectory)
    copy /b *.zip.00* newzip.zip
    powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('newzip.zip', 'bar'); }"
    cd bar
    setx DEVKITPRO "$(Agent.TempDirectory)/bar/devkitPro"
    setx DEVKITARM "$(Agent.TempDirectory)/bar/devkitPro/devkitARM"
    set
    echo test
  displayName: 'Run a multi-line script'

- script: |
    set
    echo %DEVKITARM%
  displayName: 'Run a multi-line script2'